twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    webmaster: "%env(WEBMASTER)%"
    website_name: "%env(WEBSITE_NAME)%"
    website_version: "%env(WEBSITE_VERSION)%"
#  form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    